---
# DEPLOYMENT-MVIEW
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mview
  labels:
    product: asbackend
    group: feed
    pod: mview
    app: mview
spec:
  replicas: 1
  selector:
    matchLabels:
      product: asbackend
      group: feed
      pod: mview
      app: mview
  template:
    metadata:
      labels:
        product: asbackend
        group: feed
        pod: mview
        app: mview
    spec:
      containers:
      - name: container-mview
        image: mview:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: secret-alertdb-mview-creds
        - secretRef:
            name: secret-evidencedb-mview-creds
        ports:
        - name: mview
          containerPort: 4370
        readinessProbe:
          tcpSocket:
            port: mview
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: mview
          initialDelaySeconds: 5
          periodSeconds: 15
        volumeMounts:
        - name: etc-socsettings
          mountPath: /etc/socsettings.conf
          subPath: socsettings.conf
          readOnly: true
      volumes:
      - name: etc-socsettings
        secret:
          secretName: secret-mview-socsettings

