---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspod-evidencedb-volume-claim
  labels:
    product: asbackend
    group: persistence
    pod: mongodb
    app: evidencedb
spec:
  storageClassName: "azure-disk-xfs"
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi

