---
apiVersion: v1
kind: Service
metadata:
  name: service-evidencedb
  labels:
    product: asbackend
    group: persistence
    pod: mongodb
    app: evidencedb
spec:
  selector:
    app: evidencedb
  ports:
  - name: mongodb
    port: 27017

