---
apiVersion: v1
kind: Service
metadata:
  name: service-alertdb
  labels:
    product: asbackend
    group: persistence
    pod: mongodb
    app: alertdb
spec:
  selector:
    app: alertdb
  ports:
  - name: mongodb
    port: 27017

