---
# STATEFULSET-ALERTDB
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-alertdb
  labels:
    product: asbackend
    group: persistence
    pod: mongodb
    app: alertdb
spec:
  replicas: 1
  selector:
    matchLabels:
      product: asbackend
      group: persistence
      pod: mongodb
      app: alertdb
  serviceName: alertdb
  template:
    metadata:
      labels:
        product: asbackend
        group: persistence
        pod: mongodb
        app: alertdb
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: alertdb
        effect: NoExecute
      containers:
      - name: container-alertdb
        image: mongo:4.2
        command:
        - /entrypoint.sh
        resources:
          requests:
            cpu: "2000m"
            memory: "10Gi"
          limits:
            cpu: "4000m"
            memory: "10Gi"
        envFrom:
        - secretRef:
            name: secret-alertdb-charon-creds
        - secretRef:
            name: secret-alertdb-dumpster-creds
        - secretRef:
            name: secret-alertdb-guihelper-creds
        - secretRef:
            name: secret-alertdb-mview-creds
        - secretRef:
            name: secret-alertdb-pruners-creds
        - secretRef:
            name: secret-alertdb-replicator-creds
        - secretRef:
            name: secret-alertdb-root-creds
        - secretRef:
            name: secret-alertdb-stalker-creds
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: $(ALERTDB_ROOT_USERNAME)
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: $(ALERTDB_ROOT_PASSWORD)
        ports:
        - name: mongodb
          containerPort: 27017
        lifecycle:
          postStart:
            exec:
              command:
              - /setup.sh
        startupProbe:
          exec:
            command:
            - mongo
            - --tls
            - --tlsAllowInvalidCertificates
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 60
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mongo
            - --tls
            - --tlsAllowInvalidCertificates
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        volumeMounts:
        - name: sys
          mountPath: /rootfs/sys
        - name: alertdb-data-volume
          mountPath: /data/alertdb
        - name: entrypoint-sh
          mountPath: /entrypoint.sh
          subPath: entrypoint.sh
          readOnly: true
        - name: setup-sh
          mountPath: /setup.sh
          subPath: setup.sh
          readOnly: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: alertdb-data-volume
        persistentVolumeClaim:
          claimName: aspod-alertdb-volume-claim
      - name: entrypoint-sh
        configMap:
          name: configmap-alertdb-entrypoint
          defaultMode: 0311
      - name: setup-sh
        configMap:
          name: configmap-alertdb-setup
          defaultMode: 0311

